version: '3.8'

services:
  # Service cho Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-api
    ports:
      - "8080:8080"
    volumes:
      - api-volume:/app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Service cho MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

# Khai báo các volumes
volumes:
  api-volume:
  db-volume:
